language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run lint:script
  - npm run lint:stylesheet
  - npm run type:check:focus
  - npm run test:coverage
  - npm run build
after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run test:coverage:ci
deploy:
  provider: heroku
  app:
    develop: setup-react-app-dev
    master: setup-react-app
    staging: setup-react-app-staging
  api_key:
    secure: $HEROKU_API_KEY
