// flow-typed signature: 9b99be7fbe260d99dcc58e0c739130c6
// flow-typed version: <<STUB>>/open-iconic_v^1.1.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open-iconic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open-iconic' {
  declare module.exports: any;
}
